import pandas as pd
from sqlalchemy import Engine

dates = {
        "date1": '2026-01-01',
        "date2": '2026-01-02'
}


def get_giro_camas(engine: Engine, query: str):
    df = pd.read_sql(query,engine)
    return df

query = f""" SELECT 
DISTINCT ADNCENATE.ACANOMBRE AS SEDE,genpacien.PACNUMDOC AS IDENTIFICACION, genpacien.GPANOMCOM AS PACIENTE, 
GDENOMBRE AS PLAN_BENEFICIOS,
AINCONSEC AS INGRESO,
HPNDEFCAM.HCACODIGO AS CAMA,
HPNSUBGRU.HSUCODIGO,
HPNSUBGRU.HSUNOMBRE AS SERVICIO,
HPNESTANC.HESFECING AS INICIO,
HESFECSAL AS FIN,
ADNINGRESO.AINOBSERV
FROM HPNESTANC
INNER JOIN ADNINGRESO ON ADNINGRESO.OID= HPNESTANC.ADNINGRES
INNER JOIN HPNDEFCAM ON HPNDEFCAM.OID = HPNESTANC.HPNDEFCAM
INNER JOIN HPNSUBGRU ON HPNSUBGRU.OID = HPNDEFCAM.HPNSUBGRU
INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
INNER JOIN GENDETCON ON GENDETCON.OID = ADNINGRESO.GENDETCON
INNER JOIN ADNCENATE ON ADNCENATE.OID = HPNDEFCAM.ADNCENATE
WHERE HESFECING >= '2026-02-01'
AND HESFECING < '2026-03-02'
AND ADNCENATE.ACANOMBRE = 'ALTA COMPLEJIDAD DEL CARIBE'
--AND ADNINGRESO.ADNCENATE= 'ALTA COMPLEJIDAD DEL CARIBE'
--AND HCACODIGO='ACHOSPRE8D'
UNION 
SELECT DISTINCT ADNCENATE.ACANOMBRE AS SEDE,genpacien.PACNUMDOC AS IDENTIFICACION
,genpacien.GPANOMCOM AS PACIENTE,GDENOMBRE AS PLAN_BENEFICIOS,
AINCONSEC AS INGRESO,
HPNDEFCAM.HCACODIGO AS CAMA,
HPNSUBGRU.HSUCODIGO,
HPNSUBGRU.HSUNOMBRE AS SERVICIO,
HPNESTANC.HESFECING AS INICIO,
HESFECSAL AS FIN,
ADNINGRESO.AINOBSERV
FROM HPNESTANC
INNER JOIN ADNINGRESO ON ADNINGRESO.OID= HPNESTANC.ADNINGRES
INNER JOIN HPNDEFCAM ON HPNDEFCAM.OID = HPNESTANC.HPNDEFCAM
INNER JOIN HPNSUBGRU ON HPNSUBGRU.OID = HPNDEFCAM.HPNSUBGRU
INNER JOIN GENPACIEN ON GENPACIEN.OID = ADNINGRESO.GENPACIEN
INNER JOIN GENDETCON ON GENDETCON.OID = ADNINGRESO.GENDETCON
INNER JOIN ADNCENATE ON ADNCENATE.OID = HPNDEFCAM.ADNCENATE

WHERE HESFECING >= '2026-02-01'
AND HESFECING < '2026-03-02'
AND ADNCENATE.ACANOMBRE = 'ALTA COMPLEJIDAD DEL CARIBE'
--AND ADNINGRESO.ADNCENATE= 'ALTA COMPLEJIDAD DEL CARIBE'
--AND HCACODIGO='ACHOSPRE8D'
ORDER BY 5,8 """