import pandas as pd
from sqlalchemy import Engine

dates = {
        "date1": '2026-01-01',
        "date2": '2026-01-02'
}


def get_giro_camas(engine: Engine) -> pd.DataFrame:
    print(f"📅 Consultando datos desde 2026 en adelante...")

    query = """
        SELECT DISTINCT
			HPNESTANC.OID AS ID,
            ADNCENATE.ACANOMBRE  AS SEDE,
            GENPACIEN.PACNUMDOC  AS IDENTIFICACION,
            GENPACIEN.GPANOMCOM  AS PACIENTE,
            GDENOMBRE             AS PLAN_BENEFICIOS,
            AINCONSEC             AS INGRESO,
            HPNDEFCAM.HCACODIGO  AS CAMA,
			CACCCANTCAMSER.CANTIDAD_CAMAS,
            HPNSUBGRU.HSUCODIGO,
            HPNSUBGRU.HSUNOMBRE  AS SERVICIO,
            HPNESTANC.HESFECING  AS INICIO,
            HESFECSAL             AS FIN,
			HPNDEFCAM.HCANOMBRE AS CATEGORIA,
			HPNESTANC.HESFECING AS INICIO_OCUPACION_CAMA,
			HPNESTANC.HESFECSAL AS FIN_OCUPACION_CAMA,
            ADNINGRESO.AINOBSERV

        FROM HPNESTANC
        INNER JOIN ADNINGRESO ON ADNINGRESO.OID = HPNESTANC.ADNINGRES
        INNER JOIN HPNDEFCAM  ON HPNDEFCAM.OID  = HPNESTANC.HPNDEFCAM
        INNER JOIN HPNSUBGRU  ON HPNSUBGRU.OID  = HPNDEFCAM.HPNSUBGRU
        INNER JOIN GENPACIEN  ON GENPACIEN.OID  = ADNINGRESO.GENPACIEN
        INNER JOIN GENDETCON  ON GENDETCON.OID  = ADNINGRESO.GENDETCON
        INNER JOIN ADNCENATE  ON ADNCENATE.OID  = HPNDEFCAM.ADNCENATE
		LEFT JOIN CACCCANTCAMSER ON HPNSUBGRU.HSUCODIGO = CACCCANTCAMSER.HSUCODIGO

        WHERE HPNESTANC.HESFECING >= '2026-01-01'
		--AND HCACODIGO='ACHOSPRE8D'
		AND ADNCENATE.OID = '2'

        UNION

        SELECT DISTINCT
			HPNESTANC.OID AS ID,
            ADNCENATE.ACANOMBRE  AS SEDE,
            GENPACIEN.PACNUMDOC  AS IDENTIFICACION,
            GENPACIEN.GPANOMCOM  AS PACIENTE,
            GDENOMBRE             AS PLAN_BENEFICIOS,
            AINCONSEC             AS INGRESO,
            HPNDEFCAM.HCACODIGO  AS CAMA,
			CACCCANTCAMSER.CANTIDAD_CAMAS,
            HPNSUBGRU.HSUCODIGO,
            HPNSUBGRU.HSUNOMBRE  AS SERVICIO,
            HPNESTANC.HESFECING  AS INICIO,
            HESFECSAL             AS FIN,
			HPNDEFCAM.HCANOMBRE AS CATEGORIA,
			HPNESTANC.HESFECING AS INICIO_OCUPACION_CAMA,
			HPNESTANC.HESFECSAL AS FIN_OCUPACION_CAMA,
            ADNINGRESO.AINOBSERV
        FROM HPNESTANC
        INNER JOIN ADNINGRESO ON ADNINGRESO.OID = HPNESTANC.ADNINGRES
        INNER JOIN HPNDEFCAM  ON HPNDEFCAM.OID  = HPNESTANC.HPNDEFCAM
        INNER JOIN HPNSUBGRU  ON HPNSUBGRU.OID  = HPNDEFCAM.HPNSUBGRU
        INNER JOIN GENPACIEN  ON GENPACIEN.OID  = ADNINGRESO.GENPACIEN
        INNER JOIN GENDETCON  ON GENDETCON.OID  = ADNINGRESO.GENDETCON
        INNER JOIN ADNCENATE  ON ADNCENATE.OID  = HPNDEFCAM.ADNCENATE
		LEFT JOIN CACCCANTCAMSER ON HPNSUBGRU.HSUCODIGO = CACCCANTCAMSER.HSUCODIGO
        WHERE HESFECSAL >= '2026-01-01'
		--AND HCACODIGO='ACHOSPRE8D'
		AND ADNCENATE.OID = '2'
		
        ORDER BY 5, 8
    """
    df = pd.read_sql(query, engine)
    print(f"Estamos en Services y este es el resultado: {len(df)}")
    return df